version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_taskmanager
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taskmanagerdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
